version: '3.8'


services:
  dbuser: 
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./Travelo.BE.Users/.env
    container_name: travelo_db_users
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    volumes:
      - dbuser:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - travelo_user_network
  userapp:
    depends_on:
      - dbuser
    restart: unless-stopped
    build: ./Travelo.BE.Users
    ports:
      - 8000:8000
    networks:
      - travelo_user_network
  apigateway:
    depends_on:
      - dbuser
      - userapp
    restart: unless-stopped
    build: ./Travelo.BE.Gateway
    environment:
      - API_USER=userapp
    ports:
      - 5000:5000
    networks:
      - travelo_user_network

networks:
  travelo_user_network:
    name: travelo_user_network

volumes: 
  dbuser:



